# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true
cache: packages
r:
  - devel
  - release

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(line_exclusions="R/zzz.R", type="all")'
