# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true
cache: packages

r: devel
# avoind errors due to world clock API (hopefully can be removed in future)
env: _R_CHECK_SYSTEM_CLOCK_=false

r: release

r_packages:
  - coalitions # for building pkgdown vignettes via travis

r_github_packages:
  - jimhester/covr

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: false
  local-dir: docs
  on:
    branch: master
