language: r
sudo: false
cache: packages

before_install:
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

r:
  - devel
  - release

r_packages:
  - coalitions # for building pkgdown vignettes via travis
  - pkgdown # for building homepage

r_github_packages:
  - jimhester/covr

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: false
  local-dir: docs
  on:
    branch: master
