<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Workflow • coalitions</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Workflow">
<meta property="og:description" content="">
<meta property="og:image" content="https://adibender.github.io/coalitions/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-44545040-2"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-44545040-2');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">coalitions</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.6.5</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/diagnostic.html">Diagnostic</a>
    </li>
    <li>
      <a href="../articles/pooling.html">Pooling</a>
    </li>
    <li>
      <a href="../articles/workflow.html">Workflow</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/adibender/coalitions/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Workflow</h1>
                        <h4 class="author">Andreas Bender</h4>
            
            <h4 class="date">2018-10-06</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/adibender/coalitions//blob/master/vignettes/workflow.Rmd"><code>vignettes/workflow.Rmd</code></a></small>
      <div class="hidden name"><code>workflow.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(tidyr)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">library</span>(purrr)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">library</span>(coalitions)</a></code></pre></div>
<p>In this vignette we demonstrate the basic workflow using the most recent <em>Emnid</em> survey.</p>
<div id="overview" class="section level2">
<h2 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h2>
<p>This package calculates coalition probabilities in multi-party systems. To this end we provide some convenience functions, the most important of which are listed below:</p>
<ol style="list-style-type: decimal">
<li><p><code>scrape_wahlrecht</code>: A wrapper function that download the most current survey results from <a href="https://www.wahlrecht.de/" class="uri">https://www.wahlrecht.de/</a></p></li>
<li><p><code>collapse_parties</code>: Transforms information on percentages received by individual parties in long format and stores them inside a nested tibble (see <code><a href="http://www.rdocumentation.org/packages/tidyr/topics/nest">tidyr::nest</a></code>)</p></li>
<li><p><code>draw_from_posterior</code>: Draws <code>nsim</code> samples from the posterior distribution (i.e. <code>nsim</code> simulated election results based on provided survey)</p></li>
<li><p><code>get_seats</code>: Obtain seat distributions for each simulation (see also <code><a href="../reference/sls.html">?sls</a></code>)</p></li>
<li><p><code>have_majority</code>: Given a list of coalitions of interest, calculates if the respective coalition would have enough seats for a majority</p></li>
<li><p><code>calculate_probs</code>: Given majority tables obtained from <code>have_majority</code>, calculates the probabilities for the respective coalitions to have enough seats for a majority</p></li>
</ol>
</div>
<div id="read-in-data" class="section level2">
<h2 class="hasAnchor">
<a href="#read-in-data" class="anchor"></a>Read in data</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="co"># one line per survey (party information in wide format)</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2">emnid &lt;-<span class="st"> </span><span class="kw"><a href="../reference/scrape.html">scrape_wahlrecht</a></span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</a>
<a class="sourceLine" id="cb2-3" data-line-number="3">emnid <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(<span class="op">-</span>start, <span class="op">-</span>end)</a></code></pre></div>
<pre><code>##         date cdu spd greens fdp left afd others respondents
## 1 2018-09-29  27  16     15  10   11  17      4        1902
## 2 2018-09-22  28  17     14   9   11  16      5        2368
## 3 2018-09-15  30  18     13   9   10  15      5        1978
## 4 2018-09-08  29  17     14   9   10  15      6        2472
## 5 2018-09-01  30  19     14   9    9  15      4        2390
## 6 2018-08-25  30  18     15   9    9  14      5        1891</code></pre>
</div>
<div id="collapse-survey-data" class="section level2">
<h2 class="hasAnchor">
<a href="#collapse-survey-data" class="anchor"></a>Collapse survey data</h2>
<p>After applying <code>collapse_parties</code> we still have one row per survey, but information on parties and percentage of votes they received is stored in a long format in a separate column (see <code><a href="http://www.rdocumentation.org/packages/tidyr/topics/nest">?tidyr::nest</a></code>):</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">elong &lt;-<span class="st"> </span><span class="kw"><a href="../reference/collapse_parties.html">collapse_parties</a></span>(emnid)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="kw">head</span>(elong)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   date       start      end        respondents survey          
##   &lt;date&gt;     &lt;date&gt;     &lt;date&gt;           &lt;dbl&gt; &lt;list&gt;          
## 1 2018-09-29 2018-09-20 2018-09-26        1902 &lt;tibble [7 × 3]&gt;
## 2 2018-09-22 2018-09-13 2018-09-19        2368 &lt;tibble [7 × 3]&gt;
## 3 2018-09-15 2018-09-06 2018-09-12        1978 &lt;tibble [7 × 3]&gt;
## 4 2018-09-08 2018-08-30 2018-09-05        2472 &lt;tibble [7 × 3]&gt;
## 5 2018-09-01 2018-08-23 2018-08-29        2390 &lt;tibble [7 × 3]&gt;
## 6 2018-08-25 2018-08-16 2018-08-22        1891 &lt;tibble [7 × 3]&gt;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(survey) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 7 x 3
##   party  percent votes
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1 cdu         27 514. 
## 2 spd         16 304. 
## 3 greens      15 285. 
## 4 fdp         10 190. 
## 5 left        11 209. 
## 6 afd         17 323. 
## 7 others       4  76.1</code></pre>
</div>
<div id="simulate-elections" class="section level2">
<h2 class="hasAnchor">
<a href="#simulate-elections" class="anchor"></a>Simulate elections</h2>
<p>Based on each survey we can now simulate <code>nsim</code> elections by drawing from the Dirichlet distribution</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1</span>)     <span class="co"># for reproducibility</span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"></a>
<a class="sourceLine" id="cb8-3" data-line-number="3">elong &lt;-<span class="st"> </span>elong <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span>(<span class="dt">draws =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/purrr/topics/map">map</a></span>(survey, draw_from_posterior, <span class="dt">nsim=</span><span class="dv">10</span>, <span class="dt">correction=</span><span class="fl">0.005</span>))</a>
<a class="sourceLine" id="cb8-5" data-line-number="5">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(date, survey, draws)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   date       survey           draws            
##   &lt;date&gt;     &lt;list&gt;           &lt;list&gt;           
## 1 2018-09-29 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;
## 2 2018-09-22 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;
## 3 2018-09-15 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;
## 4 2018-09-08 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;
## 5 2018-09-01 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;
## 6 2018-08-25 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="co"># each row is one election simulation</span></a>
<a class="sourceLine" id="cb10-2" data-line-number="2">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(draws) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 10 x 7
##      cdu   spd greens    fdp  left   afd others
##    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 0.259 0.151  0.162 0.112  0.105 0.179 0.0316
##  2 0.273 0.164  0.158 0.0947 0.102 0.169 0.0388
##  3 0.265 0.168  0.138 0.101  0.111 0.171 0.0453
##  4 0.273 0.149  0.149 0.101  0.113 0.170 0.0456
##  5 0.270 0.163  0.130 0.105  0.115 0.175 0.0426
##  6 0.259 0.163  0.157 0.0931 0.104 0.184 0.0389
##  7 0.267 0.163  0.154 0.0922 0.109 0.184 0.0307
##  8 0.280 0.161  0.142 0.0926 0.110 0.175 0.0402
##  9 0.258 0.161  0.155 0.0933 0.114 0.178 0.0408
## 10 0.276 0.174  0.137 0.0929 0.122 0.165 0.0324</code></pre>
</div>
<div id="calculate-seat-distribution" class="section level2">
<h2 class="hasAnchor">
<a href="#calculate-seat-distribution" class="anchor"></a>Calculate seat distribution</h2>
<p>Given the simulated elections, we can calculate the number of seats each party obtained. To do so we need to have a function that knows how to redistribute seats for the particular election. In Germany for example, seats are distributed according to the system of <em>Sainte-Lague-Scheppers</em>, which is implemented in <code><a href="../reference/sls.html">?sls</a></code>.</p>
<p>This makes this package easily extensible to other multi-party systems, as you only need to provide a function that redistributes seats based on percentages obtained by the various parties and provide that function to the <code>distrib.fun</code> argument of the <code>get_seats</code> function:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">elong &lt;-<span class="st"> </span>elong <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb12-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span>(<span class="dt">seats =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/purrr/topics/map2">map2</a></span>(draws, survey, get_seats, <span class="dt">distrib.fun=</span>sls))</a>
<a class="sourceLine" id="cb12-3" data-line-number="3">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(date, survey, draws, seats)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   date       survey           draws             seats            
##   &lt;date&gt;     &lt;list&gt;           &lt;list&gt;            &lt;list&gt;           
## 1 2018-09-29 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;
## 2 2018-09-22 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;
## 3 2018-09-15 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;
## 4 2018-09-08 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;
## 5 2018-09-01 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;
## 6 2018-08-25 &lt;tibble [7 × 3]&gt; &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt;</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">## sim column indicates simulated elections (rows in draws column)</a>
<a class="sourceLine" id="cb14-2" data-line-number="2">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(seats) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 60 x 3
##      sim party  seats
##    &lt;int&gt; &lt;chr&gt;  &lt;int&gt;
##  1     1 cdu      160
##  2     1 spd       93
##  3     1 greens   100
##  4     1 fdp       69
##  5     1 left      65
##  6     1 afd      111
##  7     2 cdu      170
##  8     2 spd      102
##  9     2 greens    98
## 10     2 fdp       59
## # ... with 50 more rows</code></pre>
<p>In the above example, given the latest survey, CDU/CSU would have 160 seats in the first simulation, 170 seats in the second simulation, etc.</p>
</div>
<div id="calculate-majorities" class="section level2">
<h2 class="hasAnchor">
<a href="#calculate-majorities" class="anchor"></a>Calculate majorities</h2>
<p>The next step is to define coalitions of interest, then calculate in what percentage of the simulations the coalition would obtain enough seats for a majority.</p>
<p>Below, each list element defines one coalition of interest (one party could potentially obtain absolute majority on their own):</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">coalitions &lt;-<span class="st"> </span><span class="kw">list</span>(</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">    <span class="kw">c</span>(<span class="st">"cdu"</span>),</a>
<a class="sourceLine" id="cb16-3" data-line-number="3">    <span class="kw">c</span>(<span class="st">"cdu"</span>, <span class="st">"fdp"</span>),</a>
<a class="sourceLine" id="cb16-4" data-line-number="4">    <span class="kw">c</span>(<span class="st">"cdu"</span>, <span class="st">"greens"</span>),</a>
<a class="sourceLine" id="cb16-5" data-line-number="5">    <span class="kw">c</span>(<span class="st">"cdu"</span>, <span class="st">"fdp"</span>, <span class="st">"greens"</span>),</a>
<a class="sourceLine" id="cb16-6" data-line-number="6">    <span class="kw">c</span>(<span class="st">"spd"</span>),</a>
<a class="sourceLine" id="cb16-7" data-line-number="7">    <span class="kw">c</span>(<span class="st">"spd"</span>, <span class="st">"left"</span>),</a>
<a class="sourceLine" id="cb16-8" data-line-number="8">    <span class="kw">c</span>(<span class="st">"spd"</span>, <span class="st">"greens"</span>),</a>
<a class="sourceLine" id="cb16-9" data-line-number="9">    <span class="kw">c</span>(<span class="st">"spd"</span>, <span class="st">"left"</span>, <span class="st">"greens"</span>),</a>
<a class="sourceLine" id="cb16-10" data-line-number="10">    <span class="kw">c</span>(<span class="st">"cdu"</span>, <span class="st">"spd"</span>))</a>
<a class="sourceLine" id="cb16-11" data-line-number="11"></a>
<a class="sourceLine" id="cb16-12" data-line-number="12"></a>
<a class="sourceLine" id="cb16-13" data-line-number="13">elong &lt;-<span class="st"> </span>elong <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb16-14" data-line-number="14"><span class="st">    </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span>(<span class="dt">majorities =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/purrr/topics/map">map</a></span>(seats, have_majority, <span class="dt">coalitions=</span>coalitions))</a>
<a class="sourceLine" id="cb16-15" data-line-number="15">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(date, draws, seats, majorities)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   date       draws             seats             majorities       
##   &lt;date&gt;     &lt;list&gt;            &lt;list&gt;            &lt;list&gt;           
## 1 2018-09-29 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;
## 2 2018-09-22 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;
## 3 2018-09-15 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;
## 4 2018-09-08 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;
## 5 2018-09-01 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;
## 6 2018-08-25 &lt;tibble [10 × 7]&gt; &lt;tibble [60 × 3]&gt; &lt;tibble [10 × 9]&gt;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="co"># The majorities table for each date will have 1 row per simulation</span></a>
<a class="sourceLine" id="cb18-2" data-line-number="2"><span class="co"># and one column per coalition</span></a>
<a class="sourceLine" id="cb18-3" data-line-number="3">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(majorities) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 10 x 9
##    cdu   cdu_fdp cdu_greens cdu_fdp_greens spd   left_spd greens_spd
##    &lt;lgl&gt; &lt;lgl&gt;   &lt;lgl&gt;      &lt;lgl&gt;          &lt;lgl&gt; &lt;lgl&gt;    &lt;lgl&gt;     
##  1 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  2 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  3 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  4 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  5 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  6 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  7 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  8 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
##  9 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
## 10 FALSE FALSE   FALSE      TRUE           FALSE FALSE    FALSE     
## # ... with 2 more variables: greens_left_spd &lt;lgl&gt;, cdu_spd &lt;lgl&gt;</code></pre>
</div>
<div id="calculate-coalition-probabilities" class="section level2">
<h2 class="hasAnchor">
<a href="#calculate-coalition-probabilities" class="anchor"></a>Calculate coalition probabilities</h2>
<p>The last step is to calculate the coalition probabilities (note that by default we exclude “superior” coalitions, i.e. if “cdu/csu” have a majority on their own, this simulation will not be counted to the simulation with majority for “cdu/csu” and “fdp”, see example in <code><a href="../reference/calculate_probs.html">?calculate_probs</a></code>):</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">elong &lt;-<span class="st"> </span>elong <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb20-2" data-line-number="2"><span class="st">    </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span>(</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">        <span class="dt">probabilities =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/purrr/topics/map">map</a></span>(majorities, calculate_probs, <span class="dt">coalitions=</span>coalitions))</a>
<a class="sourceLine" id="cb20-4" data-line-number="4">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(date, majorities, probabilities)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   date       majorities        probabilities   
##   &lt;date&gt;     &lt;list&gt;            &lt;list&gt;          
## 1 2018-09-29 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;
## 2 2018-09-22 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;
## 3 2018-09-15 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;
## 4 2018-09-08 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;
## 5 2018-09-01 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;
## 6 2018-08-25 &lt;tibble [10 × 9]&gt; &lt;tibble [9 × 2]&gt;</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="co"># one row per coalition</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/slice.html">slice</a></span>(<span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/select.html">select</a></span>(probabilities) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##   coalition       probability
##   &lt;chr&gt;                 &lt;dbl&gt;
## 1 cdu                       0
## 2 cdu_fdp                   0
## 3 cdu_greens                0
## 4 cdu_fdp_greens          100
## 5 spd                       0
## 6 left_spd                  0
## 7 greens_spd                0
## 8 greens_left_spd           0
## 9 cdu_spd                   0</code></pre>
</div>
<div id="wrapper" class="section level2">
<h2 class="hasAnchor">
<a href="#wrapper" class="anchor"></a>Wrapper</h2>
<p>There is a wrapper function that directly returns probabilities:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">elong &lt;-<span class="st"> </span><span class="kw"><a href="../reference/collapse_parties.html">collapse_parties</a></span>(emnid)</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">elong <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/get_probabilities.html">get_probabilities</a></span>(., <span class="dt">nsim=</span><span class="dv">10</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/tidyr/topics/unnest">unnest</a></span>()</a></code></pre></div>
<pre><code>## # A tibble: 36 x 3
##    date       coalition       probability
##    &lt;date&gt;     &lt;chr&gt;                 &lt;dbl&gt;
##  1 2018-09-29 cdu                       0
##  2 2018-09-29 cdu_fdp                   0
##  3 2018-09-29 cdu_fdp_greens          100
##  4 2018-09-29 spd                       0
##  5 2018-09-29 left_spd                  0
##  6 2018-09-29 greens_left_spd           0
##  7 2018-09-22 cdu                       0
##  8 2018-09-22 cdu_fdp                   0
##  9 2018-09-22 cdu_fdp_greens          100
## 10 2018-09-22 spd                       0
## # ... with 26 more rows</code></pre>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#overview">Overview</a></li>
      <li><a href="#read-in-data">Read in data</a></li>
      <li><a href="#collapse-survey-data">Collapse survey data</a></li>
      <li><a href="#simulate-elections">Simulate elections</a></li>
      <li><a href="#calculate-seat-distribution">Calculate seat distribution</a></li>
      <li><a href="#calculate-majorities">Calculate majorities</a></li>
      <li><a href="#calculate-coalition-probabilities">Calculate coalition probabilities</a></li>
      <li><a href="#wrapper">Wrapper</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Andreas Bender, Alexander Bauer.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script><script>
  docsearch({
    
    
    apiKey: 'b07f33bbc5aa2eddd7d63f5c8473e333',
    indexName: 'coalitions',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
